version: '3.8'

services:
  # PHP Application with Apache
  web:
    image: php-mysql
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d  # Adding a custom init script
    networks:
      - app-network

# Docker Volumes
volumes:
  db_data:

# Docker Networks
networks:
  app-network:
    driver: bridge